name: 'imago'

services:
  rabbit:
    image: rabbitmq:4.3.5-management
    env_file: .env
    environment:
        - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
        - "5672:5672"
        - "15672:15672"
    volumes:
        - rabbit-data:/var/lib/rabbitmq

  redis:
    image: redis:8.8.2
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - redis-data:/root/redis
      - redis-data:/usr/local/etc/redis/redis.conf
      - redis-data:/dump.rdb

volumes:
  rabbit-data:
  redis-data:

